/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourRouteImport } from './routes/tour'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ScheduleDataRouteImport } from './routes/schedule-data'
import { Route as PreservationRouteImport } from './routes/preservation'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as HardshipThreadRouteImport } from './routes/hardship-thread'
import { Route as GregAnitaThreadRouteImport } from './routes/greg-anita-thread'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ComparatorsRouteImport } from './routes/comparators'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CaseMapRouteImport } from './routes/case-map'
import { Route as IndexRouteImport } from './routes/index'

const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDataRoute = ScheduleDataRouteImport.update({
  id: '/schedule-data',
  path: '/schedule-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PreservationRoute = PreservationRouteImport.update({
  id: '/preservation',
  path: '/preservation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorRoute = InvestigatorRouteImport.update({
  id: '/investigator',
  path: '/investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const HardshipThreadRoute = HardshipThreadRouteImport.update({
  id: '/hardship-thread',
  path: '/hardship-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const GregAnitaThreadRoute = GregAnitaThreadRouteImport.update({
  id: '/greg-anita-thread',
  path: '/greg-anita-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatorsRoute = ComparatorsRouteImport.update({
  id: '/comparators',
  path: '/comparators',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseMapRoute = CaseMapRouteImport.update({
  id: '/case-map',
  path: '/case-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-map': typeof CaseMapRoute
  '/command': typeof CommandRoute
  '/comparators': typeof ComparatorsRoute
  '/evidence': typeof EvidenceRoute
  '/greg-anita-thread': typeof GregAnitaThreadRoute
  '/hardship-thread': typeof HardshipThreadRoute
  '/investigator': typeof InvestigatorRoute
  '/people': typeof PeopleRoute
  '/performance': typeof PerformanceRoute
  '/preservation': typeof PreservationRoute
  '/schedule-data': typeof ScheduleDataRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/tour': typeof TourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-map': typeof CaseMapRoute
  '/command': typeof CommandRoute
  '/comparators': typeof ComparatorsRoute
  '/evidence': typeof EvidenceRoute
  '/greg-anita-thread': typeof GregAnitaThreadRoute
  '/hardship-thread': typeof HardshipThreadRoute
  '/investigator': typeof InvestigatorRoute
  '/people': typeof PeopleRoute
  '/performance': typeof PerformanceRoute
  '/preservation': typeof PreservationRoute
  '/schedule-data': typeof ScheduleDataRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/tour': typeof TourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-map': typeof CaseMapRoute
  '/command': typeof CommandRoute
  '/comparators': typeof ComparatorsRoute
  '/evidence': typeof EvidenceRoute
  '/greg-anita-thread': typeof GregAnitaThreadRoute
  '/hardship-thread': typeof HardshipThreadRoute
  '/investigator': typeof InvestigatorRoute
  '/people': typeof PeopleRoute
  '/performance': typeof PerformanceRoute
  '/preservation': typeof PreservationRoute
  '/schedule-data': typeof ScheduleDataRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/tour': typeof TourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-map'
    | '/command'
    | '/comparators'
    | '/evidence'
    | '/greg-anita-thread'
    | '/hardship-thread'
    | '/investigator'
    | '/people'
    | '/performance'
    | '/preservation'
    | '/schedule-data'
    | '/story'
    | '/timeline'
    | '/tour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-map'
    | '/command'
    | '/comparators'
    | '/evidence'
    | '/greg-anita-thread'
    | '/hardship-thread'
    | '/investigator'
    | '/people'
    | '/performance'
    | '/preservation'
    | '/schedule-data'
    | '/story'
    | '/timeline'
    | '/tour'
  id:
    | '__root__'
    | '/'
    | '/case-map'
    | '/command'
    | '/comparators'
    | '/evidence'
    | '/greg-anita-thread'
    | '/hardship-thread'
    | '/investigator'
    | '/people'
    | '/performance'
    | '/preservation'
    | '/schedule-data'
    | '/story'
    | '/timeline'
    | '/tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseMapRoute: typeof CaseMapRoute
  CommandRoute: typeof CommandRoute
  ComparatorsRoute: typeof ComparatorsRoute
  EvidenceRoute: typeof EvidenceRoute
  GregAnitaThreadRoute: typeof GregAnitaThreadRoute
  HardshipThreadRoute: typeof HardshipThreadRoute
  InvestigatorRoute: typeof InvestigatorRoute
  PeopleRoute: typeof PeopleRoute
  PerformanceRoute: typeof PerformanceRoute
  PreservationRoute: typeof PreservationRoute
  ScheduleDataRoute: typeof ScheduleDataRoute
  StoryRoute: typeof StoryRoute
  TimelineRoute: typeof TimelineRoute
  TourRoute: typeof TourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-data': {
      id: '/schedule-data'
      path: '/schedule-data'
      fullPath: '/schedule-data'
      preLoaderRoute: typeof ScheduleDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preservation': {
      id: '/preservation'
      path: '/preservation'
      fullPath: '/preservation'
      preLoaderRoute: typeof PreservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator': {
      id: '/investigator'
      path: '/investigator'
      fullPath: '/investigator'
      preLoaderRoute: typeof InvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardship-thread': {
      id: '/hardship-thread'
      path: '/hardship-thread'
      fullPath: '/hardship-thread'
      preLoaderRoute: typeof HardshipThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/greg-anita-thread': {
      id: '/greg-anita-thread'
      path: '/greg-anita-thread'
      fullPath: '/greg-anita-thread'
      preLoaderRoute: typeof GregAnitaThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparators': {
      id: '/comparators'
      path: '/comparators'
      fullPath: '/comparators'
      preLoaderRoute: typeof ComparatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-map': {
      id: '/case-map'
      path: '/case-map'
      fullPath: '/case-map'
      preLoaderRoute: typeof CaseMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseMapRoute: CaseMapRoute,
  CommandRoute: CommandRoute,
  ComparatorsRoute: ComparatorsRoute,
  EvidenceRoute: EvidenceRoute,
  GregAnitaThreadRoute: GregAnitaThreadRoute,
  HardshipThreadRoute: HardshipThreadRoute,
  InvestigatorRoute: InvestigatorRoute,
  PeopleRoute: PeopleRoute,
  PerformanceRoute: PerformanceRoute,
  PreservationRoute: PreservationRoute,
  ScheduleDataRoute: ScheduleDataRoute,
  StoryRoute: StoryRoute,
  TimelineRoute: TimelineRoute,
  TourRoute: TourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
